export enum Privilege {
  READ_IMAGE_SHOW = 'READ_IMAGE_SHOW',
  WRITE_IMAGE_SHOW = 'WRITE_IMAGE_SHOW',
  DELETE_IMAGE_SHOW = 'DELETE_IMAGE_SHOW',

  READ_MONITORS = 'READ_MONITORS',
  WRITE_MONITORS = 'WRITE_MONITORS',
  DELETE_MONITORS = 'DELETE_MONITORS',

  READ_SUBSTITUTIONS = 'READ_SUBSTITUTIONS',
  WRITE_SUBSTITUTIONS = 'WRITE_SUBSTITUTIONS',
  DELETE_SUBSTITUTIONS = 'DELETE_SUBSTITUTIONS',

  READ_ADVERTISMENT = 'READ_ADVERTISMENT',
  WRITE_ADVERTISMENT = 'WRITE_ADVERTISMENT',
  DELETE_ADVERTISMENT = 'DELETE_ADVERTISMENT',

  READ_USER = 'READ_USER',
  WRITE_USER = 'WRITE_USER',
  DELETE_USER = 'DELETE_USER',

  WRITE_MESSAGES = 'WRITE_MESSAGES',
	READ_MESSAGES= 'READ_MESSAGES',
}
